### ISSUE TITLE
Error code: 40003

### ISSUE THREAD

**Issue by C0S1N3** [fromann/DailyWechat#1]
接收人只填了一位，虽然收到了，但还是报了40003的错，还有，tem_high的缩进有问题，你是怎么跑通的？

**Comment by cn3shy** [comment]
> 接收人只填了一位，虽然收到了，但还是报了40003的错，还有，tem_high的缩进有问题，你是怎么跑通的？

main.py 123行，
对于我个人使用
我加了一个主人ID给我反馈一共发送了多少条信息
你可以修改代码把ID换成你自己的
